# Site settings
title: "与其临渊羡鱼，不如退而结网！"
url: "jacksonzhou.cn/"
paginate: 10
author:
    name: jackson.zhou
    github: jackson-zhou
    email: jackson.zhou@live.com
# Build settings
kramdown:
    input: GFM
permalink: /:categories/:year-:month/:title.html
gems: [jekyll-paginate]
exclude: [Gemfile, Gemfile.lock, qrsync, Rakefile, docker-compose.yml]
plugins: [jekyll-paginate,kramdown-plantuml]
assets_path: /assets
sass:
    sass_dir: assets/_sass
    style: :compressed

# comment
comments:
    duoshuo:
        name:                                # short name
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26

# tinysou.com
search:
    tinysou:
        engineKey: 

# 网站统计
analytics:
    baidu:
        siteid:                             # 百度统计 js 代码后的字符串
webmaster:
    baidu:
        verify:
    google:
        verify:
    bing:
        verify:

plantuml-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: plantuml
    syntax:
      code: 'plantuml!'
      custom: ['@startuml', '@enduml']
    src: http://www.plantuml.com/plantuml/svg/
